[features]
seeds = false
skip-lint = false
[programs.localnet]
intrant_inferis_solana = "5ge4AFnyG6FsMaEVE8svaggVxzfZgLSS2KWRH2UdcPVn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/home/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
